"""add inventory movement stock snapshots

Revision ID: b5e2e983bd8a
Revises: a0719be54ccc
Create Date: 2026-10-01 11:41:31.110859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e2e983bd8a'
down_revision: Union[str, Sequence[str], None] = 'a0719be54ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_movements', sa.Column('previous_stock', sa.Integer(), nullable=False))
    op.add_column('inventory_movements', sa.Column('new_stock', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_movements', 'new_stock')
    op.drop_column('inventory_movements', 'previous_stock')
    # ### end Alembic commands ###
