"""add database integrity constraints

Revision ID: d73a134a8312
Revises: 0b7632b8b8b2
Create Date: 2026-10-03 20:07:01.775181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73a134a8312'
down_revision: Union[str, Sequence[str], None] = '0b7632b8b8b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('low_stock_threshold', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'low_stock_threshold')
    # ### end Alembic commands ###
